'use strict';
let csrf = null, online = false;
const $ = id => document.getElementById(id);
const money = n => typeof n === 'number' && Number.isFinite(n) ? new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n) : '—';
function node(tag, text, cls) {const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(cls)n.className=cls;return n;}
function message(text, warning=false){$('notice').textContent=text;$('notice').classList.toggle('warning',warning);}
async function api(path, body){const res=await fetch(path,{method:body?'POST':'GET',credentials:'same-origin',cache:'no-store',headers:body?{'Content-Type':'application/json','X-TB-CSRF':csrf||''}:{},body:body?JSON.stringify(body):undefined});const data=await res.json();if(!res.ok)throw new Error(data.error||'REQUEST_FAILED');return data;}
function showLogin(){$('workspace').hidden=true;$('pairing').hidden=false;online=false;}
async function refresh(){if(!csrf)return;try{const s=await api('/api/status');online=true;render(s);for(const id of ['pause','resume','flatten'])$(id).disabled=false;}catch(e){online=false;if(e.message==='SIGN_IN_REQUIRED'){csrf=null;showLogin();return;}$('connection-state').textContent='Disconnected';$('status-dot').classList.remove('good');message('Connection lost. Values may be stale; controls are disabled until the server responds.',true);for(const id of ['pause','resume','flatten'])$(id).disabled=true;}}
function render(s){$('equity').textContent=money(s.paper_equity);$('weekly-budget').textContent=money(s.weekly.limit);$('weekly-base').textContent='10% of '+money(s.weekly.starting_equity)+' weekly starting equity';$('capacity').textContent=money(s.remaining_entry_capacity);$('open-count').textContent=String(s.positions.length);$('engine-state').textContent=s.paused?'New entries paused':'Paper entries enabled';$('connection-state').textContent=s.healthy?'Service responding':'Service needs attention';$('status-dot').classList.toggle('good',s.healthy);$('heartbeat-age').textContent=s.heartbeat_age_seconds===null?'No verified heartbeat':Math.round(s.heartbeat_age_seconds)+'s since last heartbeat';$('build-version').textContent=s.version+' · '+s.strategy_version;$('grading').textContent=s.grading;$('coverage').textContent=s.coverage_note;
if(s.error)message('Service diagnostic: '+s.error+'. No live trading is enabled.',true);else if(s.flatten_requested)message('Paper liquidation pending: '+(s.flatten_status||'waiting for worker')+'. New entries remain paused.',true);else if(s.weekly.locked)message('Weekly loss lock is active. Resuming the app cannot override the risk limit.',true);else message('Paper workspace · '+(s.heartbeat?.session_open?'Market session open':'Market session closed or not verified')+' · No live broker order can be placed.');
const positions=$('positions-list');positions.replaceChildren();positions.className=s.positions.length?'':'empty';if(!s.positions.length)positions.textContent='No open paper positions. An empty book is a valid decision.';s.positions.forEach(p=>{const row=node('article',undefined,'position'),top=node('div',undefined,'position-top');top.append(node('strong',p.ticker+' '+p.direction.toUpperCase()),node('span',p.lane,'pill'));row.append(top,node('small',p.contract+' · expires '+p.expiration));const values=node('div',undefined,'values');for(const [k,v] of [['Entry',p.entry_fill],['Last mark',p.last_mark],['Stop',p.stop_price],['Target',p.target_price]])values.append(node('span',k+' '+money(v)));row.append(values);positions.append(row);});
const watches=$('watches');watches.replaceChildren();if(!s.watches.length)watches.append(node('p','No premarket screen loaded. Candidates are never fabricated to fill six slots.','empty'));s.watches.forEach((w,i)=>{const c=node('article',undefined,'watch');c.append(node('div',i<3?'15-MINUTE LANE':'5-MINUTE LANE','lane'),node('strong',w.ticker+' '+w.direction.toUpperCase()),node('small','Reference '+money(w.trigger)),node('small','Invalidation '+money(w.invalidation)),node('small','Source '+w.source_date));watches.append(c);});
const rej=$('rejections');rej.replaceChildren();if(!Object.keys(s.rejections).length)rej.append(node('p','No recorded rejections. This is not a coverage guarantee.','empty'));Object.entries(s.rejections).sort((a,b)=>b[1]-a[1]).slice(0,8).forEach(([k,v])=>{const row=node('div',undefined,'audit');row.append(node('span',k.replaceAll('_',' ')),node('strong',v));rej.append(row);});
const lanes=$('lanes');lanes.replaceChildren();for(const l of s.lane_stats){const c=node('div',undefined,'lane-card');c.append(node('div',l.lane==='5m_momentum'?'5-MINUTE MOMENTUM':'15-MINUTE OPTIONS','lane'),node('strong',money(l.pnl)),node('small',l.closed+' closed · expectancy '+money(l.expectancy)));lanes.append(c);}if(!s.lane_stats.length)lanes.append(node('p','Statistics appear only after records exist.','empty'));
const commands=$('commands');commands.replaceChildren();if(!s.commands.length)commands.append(node('p','No control requests.','empty'));s.commands.slice(0,5).forEach(c=>{const r=node('div',undefined,'audit');r.append(node('span',c.action.toUpperCase()),node('strong',c.status));commands.append(r);});
const trades=$('trades');trades.replaceChildren();if(!s.closed_trades.length){trades.append(node('p','No completed paper trades.','empty'));return;}trades.className='table-wrap';const table=node('table'),head=node('tr'),thead=node('thead'),tbody=node('tbody');['UNDERLYING','LANE','EXIT','NET P&L','CLOSED'].forEach(x=>head.append(node('th',x)));thead.append(head);table.append(thead);s.closed_trades.slice().reverse().forEach(t=>{const r=node('tr');r.append(node('td',t.ticker),node('td',t.lane),node('td',t.exit_reason),node('td',money(t.pnl),t.pnl>=0?'positive':'negative'),node('td',new Date(t.closed_at).toLocaleString()));tbody.append(r);});table.append(tbody);trades.append(table);}
async function command(action, confirmation){if(!online)return;try{const id=crypto.randomUUID();const result=await api('/api/command',{id,action,confirmation});message('Request '+result.status+'. The worker will apply it; this does not confirm a fill.');await refresh();}catch(e){message('Control was not confirmed: '+e.message,true);}}
$('pair-form').addEventListener('submit',async e=>{e.preventDefault();try{const r=await api('/api/login',{token:$('pair-token').value});$('pair-token').value='';csrf=r.csrf;$('pair-error').textContent='';$('pairing').hidden=true;$('workspace').hidden=false;await refresh();}catch(err){$('pair-error').textContent=err.message;}});
$('pause').onclick=()=>command('pause');$('resume').onclick=()=>command('resume');$('flatten').onclick=()=>{$('confirm-text').value='';$('close-dialog').showModal();};$('cancel-close').onclick=()=>$('close-dialog').close();$('close-form').onsubmit=e=>{e.preventDefault();if($('confirm-text').value!=='CLOSE PAPER POSITIONS'){$('confirm-text').setCustomValidity('Type CLOSE PAPER POSITIONS exactly.');$('confirm-text').reportValidity();return;}$('close-dialog').close();command('flatten','CLOSE PAPER POSITIONS');};$('confirm-text').oninput=()=>$('confirm-text').setCustomValidity('');$('logout').onclick=async()=>{try{await api('/api/logout',{});}finally{csrf=null;showLogin();}};
(async()=>{try{const s=await api('/api/session');csrf=s.csrf;$('pairing').hidden=true;$('workspace').hidden=false;await refresh();}catch(e){showLogin();}})();setInterval(refresh,5000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});if('serviceWorker' in navigator && window.isSecureContext)navigator.serviceWorker.register('/sw.js').catch(()=>{});
